In [92]:
# importing the libraries 
import pandas as pd 
import numpy as np 
from sklearn.feature_selection import SelectKBest,chi2,RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [93]:
# importing the dataset
df = pd.read_csv(r"C:\Users\sandi\Downloads\Pima.csv",index_col=0)
df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [94]:
# define X and Y 

In [95]:
x = df.iloc[:,0:-1]
y = df['class']

# Univariate analysis 

In [96]:
# Chi Square for feature selection 

In [97]:
test = SelectKBest(score_func=chi2,k=5)
chi_score = test.fit(x,y)

In [98]:
# Score function 
chi_score.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [99]:
x.columns

Index(['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], dtype='object')

In [100]:
# create a DataFrame 
Score = pd.DataFrame(chi_score.scores_,x.columns).T
Score

# or the same approach 

# Score = pd.DataFrame(chi_score.scores_).T
# Score.columns = x.columns
# Score

preg         plas       pres      skin         test        mass  \
0  111.519691  1411.887041  17.605373  53.10804  2175.565273  127.669343   

       pedi         age  
0  5.392682  181.303689

# Recursive Feature Ellimination 

In [101]:
# Rfe

In [102]:
# use the lg as a estimator 
lg = LogisticRegression(max_iter=500)

rfe = RFE(estimator=lg)

rfe.fit(x,y)

RFE(estimator=LogisticRegression(max_iter=500))

In [103]:
rfe.support_

array([ True,  True, False, False, False,  True,  True, False])

In [104]:
x.columns

Index(['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], dtype='object')

In [105]:
rank = rfe.ranking_
rank 

array([1, 1, 3, 5, 4, 1, 1, 2])

In [106]:
rfe_score = pd.DataFrame({
                          'rfe.support_' : rfe.support_,
                          'Ranking': rank
                        },index = x.columns)


rfe_score.T
 


preg  plas   pres   skin   test  mass  pedi    age
rfe.support_  True  True  False  False  False  True  True  False
Ranking          1     1      3      5      4     1     1      2

# Tree Based Method 

In [107]:
dt = DecisionTreeClassifier()

dt.fit(x,y)

DecisionTreeClassifier()

In [108]:
dt.feature_importances_

array([0.04737156, 0.33356701, 0.08607182, 0.02203383, 0.0333573 ,
       0.20772847, 0.14916336, 0.12070666])

In [109]:
SCORE = pd.DataFrame(dt.feature_importances_).T
SCORE.columns = x.columns
SCORE

preg      plas      pres      skin      test      mass      pedi  \
0  0.047372  0.333567  0.086072  0.022034  0.033357  0.207728  0.149163   

        age  
0  0.120707

In [110]:
# Plasma, mass ,age, pedi this columns are importance for our next analysis 